### ISSUE TITLE
recognize_song is deprecated

### ISSUE THREAD

**Issue by dotX12** [woodruffw/shaq#20]
Hi, I use this cli from time to time, can you fix the work with the audio segment and not use deprecated recognize_song?
https://github.com/woodruffw/shaq/blob/58b0cac4fe047d58e493e9a7870fbd0ad9904a95/shaq/_cli.py#L114

An example of how to transfer bytes from an AudioSegment is described here:
https://github.com/shazamio/ShazamIO/issues/103#issuecomment-2081220779

**Comment by woodruffw** [comment]
Thanks for the report! I don't have any immediate time to work on this, but I'll get to it eventually. In the mean time, I'd be happy to review a patch that uses the non-deprecated API in case anybody feels like tackling this.
