### ISSUE TITLE
Fail hard if `ffmpeg` isn't installed

### ISSUE THREAD

**Issue by woodruffw** [woodruffw/shaq#3]
Our dependencies require this but don't check for it.

**Comment by AtticFinder65536** [comment]
I don't know if some platforms version the ffmpeg binary name, but the commit will always fail on many systems where the name is just 'ffmpeg'. pydub also checks for 'ffmpeg' in PATH, so maybe checking is not necessary.

**Comment by woodruffw** [comment]
Nope, that was just a complete typo on my part. I'm not in front of a computer at the moment but feel free to send a PR fixing this; otherwise I'll fix it tomorrow most likely.
